### ISSUE TITLE
BUG - Tidak bisa Login

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratumproject/ignite#50]
Hallo teman2 maaf kami kembali lagi hehe ... ada beberapa bug yang terjadi barusan

bisa dilihat di video ini

https://drive.google.com/file/d/1OuKUb8LUfLer7c9DZwxiLZBAXNEPkPVU/view?usp=sharing

**Comment by nevrending** [comment]
Recording tidak jelas, URL tidak kelihatan

**Comment by radinalsuryaatmaja** [comment]
Oke sebentar ...
