### ISSUE TITLE
BUG - Tidak bisa submit artikel

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratumproject/ignite#51]
Video bisa dilihat disini

https://drive.google.com/file/d/1bVQw5QXsvsRTFayR-GprfCGlX0r8fUou/view?usp=sharing

**Comment by nevrending** [comment]
Recording tidak jelas, URL tidak kelihatan, perlu keterangan tambahan seperti hal2 yg dilakukan sebelum submit artikel, apakah itu artikel baru atau edit

**Comment by radinalsuryaatmaja** [comment]
Oke sebentar
