### ISSUE TITLE
2020 07 20 - Admin tidak bisa login

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratumproject/ignite#52]
[error-login admin.mp4.zip](https://github.com/stratumproject/ignite/files/4946453/error-login.admin.mp4.zip)

Maaf admin ignitegki.com tidak bisa login

current email : admin@ignitegki.com

current pass : admin

*bukti bisa di cek di **attachement** file ini

**Comment by nevrending** [comment]
![image](https://user-images.githubusercontent.com/4745298/87919867-c457b980-cabb-11ea-8756-6ef2622eef6a.png)

Barusan saya coba sepertinya baik2 saja. Di sistem kita juga tidak tercatat insiden error tersebut.
Jika demikian terjadi lagi, mungkin boleh dicoba buka ulang ignitegki.com lalu klik **Login** dari sana.

**Comment by radinalsuryaatmaja** [comment]
Oke, sudah beres ... sudah bisa diakses kembali

thank you
