### ISSUE TITLE
20200910-Email info@ignitegki.com bermasalah (Rejected)

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratumproject/ignite#53]
Rekan-rekan, apakah email **info@ignitegki.com** ada masalah ??

<img width="708" alt="Screen Shot 2020-09-10 at 11 46 34" src="https://user-images.githubusercontent.com/48216452/92682743-53b27800-f35b-11ea-8889-6be69edb3e08.png">

Secara teknis, dari dulu kami telah memakai email ini dan masih berfungsi semenjak develop ke sistem baru. Lalu temuan reject seperti gambar di atas ada muncul beberapa hari kemarin.

Kurang lebihnya seperti itu. Terima kasih.

**Comment by nevrending** [comment]
Dari sisi kami tidak ada perubahan. Email `info@ignitegki.com` sepertinya dari dulu dihandle oleh hosting lamanya ignite yah? Jadi mungkin bisa ditanyakan ke Pak Adi perihal hal tsb

**Comment by radinalsuryaatmaja** [comment]
OO , email dipegang hosting ya , bukan masuk di server ya ??

**Comment by nevrending** [comment]
Tidak, emailnya tidak lewat server kita

**Comment by radinalsuryaatmaja** [comment]
oke, kami sedang koordinasi dengan pak Adi. case closed :)
