### ISSUE TITLE
2020 12 10 - Tidak bisa masuk ke halaman www.ignitegki.com

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratumproject/ignite#54]
<img width="1680" alt="Screen Shot 2020-12-10 at 13 03 29" src="https://user-images.githubusercontent.com/48216452/101727989-24d9a880-3ae8-11eb-837c-85c70f8e5815.png">

Mohon bantuannya, sekian terima kasih

**Comment by nevrending** [comment]
Ada email dari kita tanggal 2 Dec 2020. Bisa coba di cek ya
Terima kasih

**Comment by radinalsuryaatmaja** [comment]
wupzz, sorry barusan cek, oke ... segera ditindaklanjuti

**Comment by radinalsuryaatmaja** [comment]
email udah dibalas dan udah ditindaklanjuti .... :)

maicih

**Comment by nevrending** [comment]
Site sudah up kembali :)
